/**
 * PulsePoint Mock Healthcare Dataset
 * Provides seeded relational mock data matching schema.sql
 */

export const INITIAL_FACILITIES = [
  {
    id: 'fac-hosp-01',
    name: 'St. Jude Academic Medical Center',
    type: 'HOSPITAL',
    license: 'HOSP-LIC-78921',
    address: '450 University Blvd, Medical District',
    district: 'Medical District',
    phone: '+1 (555) 019-2000',
    emergencyPhone: '+1 (555) 019-9111',
    isColdChainCertified: true,
    operatingHours: '24/7 Level 1 Trauma Care',
    distanceMiles: 1.2
  },
  {
    id: 'fac-hosp-02',
    name: 'Metropolitan Trauma & Surgical Center',
    type: 'HOSPITAL',
    license: 'HOSP-LIC-66102',
    address: '128 Grand Central Ave, Downtown',
    district: 'Downtown',
    phone: '+1 (555) 019-3500',
    emergencyPhone: '+1 (555) 019-9222',
    isColdChainCertified: true,
    operatingHours: '24/7 Emergency Surgery',
    distanceMiles: 2.8
  },
  {
    id: 'fac-bank-01',
    name: 'Regional Central Blood & Plasma Repository',
    type: 'BLOOD_BANK',
    license: 'BB-LIC-99014',
    address: '77 Healthway Parkway, North District',
    district: 'North District',
    phone: '+1 (555) 019-7000',
    emergencyPhone: '+1 (555) 019-7999',
    isColdChainCertified: true,
    operatingHours: '24/7 Cold-Chain Logistics Hub',
    distanceMiles: 3.5
  },
  {
    id: 'fac-pharm-01',
    name: 'Apollo 24x7 Super Care Chemist',
    type: 'PHARMACY',
    license: 'PHARM-LIC-33201',
    address: '88 Lexington Avenue, Midtown',
    district: 'Midtown',
    phone: '+1 (555) 019-4100',
    isColdChainCertified: false,
    operatingHours: 'Open 24 Hours Daily',
    distanceMiles: 0.6
  },
  {
    id: 'fac-pharm-02',
    name: 'Metro Health Pharmacy & MedStore',
    type: 'PHARMACY',
    license: 'PHARM-LIC-44109',
    address: '302 5th Avenue, Chelsea',
    district: 'Chelsea',
    phone: '+1 (555) 019-4200',
    isColdChainCertified: false,
    operatingHours: '07:00 AM - 11:30 PM',
    distanceMiles: 1.4
  },
  {
    id: 'fac-pharm-03',
    name: 'City Care Generic & Critical Drugs',
    type: 'PHARMACY',
    license: 'PHARM-LIC-55032',
    address: '15 Broadway Suite 4, Financial District',
    district: 'Financial District',
    phone: '+1 (555) 019-4300',
    isColdChainCertified: false,
    operatingHours: '08:00 AM - 10:00 PM',
    distanceMiles: 2.1
  },
  {
    id: 'fac-lab-01',
    name: 'PulsePoint Diagnostic & Molecular Imaging Hub',
    type: 'DIAGNOSTIC_LAB',
    license: 'LAB-LIC-11099',
    address: '210 Medical Center Way, Health District',
    district: 'Health District',
    phone: '+1 (555) 019-6100',
    isColdChainCertified: true,
    operatingHours: '06:30 AM - 09:00 PM',
    distanceMiles: 1.1
  }
];

export const INITIAL_MEDICINES = [
  {
    id: 'med-01',
    facilityId: 'fac-pharm-01',
    facilityName: 'Apollo 24x7 Super Care Chemist',
    name: 'Amoxicillin Trihydrate',
    genericName: 'Amoxicillin',
    dosage: '500mg',
    form: 'Capsule',
    category: 'Antibiotic',
    price: 12.50,
    stockStatus: 'IN_STOCK', // 'IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK'
    quantity: 145,
    batchNo: 'AMX-2026-B1',
    expiryDate: '2027-08-30',
    prescriptionRequired: true
  },
  {
    id: 'med-02',
    facilityId: 'fac-pharm-02',
    facilityName: 'Metro Health Pharmacy & MedStore',
    name: 'Amoxil Forte Brand',
    genericName: 'Amoxicillin',
    dosage: '500mg',
    form: 'Capsule',
    category: 'Antibiotic',
    price: 14.00,
    stockStatus: 'IN_STOCK',
    quantity: 60,
    batchNo: 'AMX-2026-M2',
    expiryDate: '2027-09-15',
    prescriptionRequired: true
  },
  {
    id: 'med-03',
    facilityId: 'fac-pharm-03',
    facilityName: 'City Care Generic & Critical Drugs',
    name: 'Generic Amoxicillin Economy',
    genericName: 'Amoxicillin',
    dosage: '500mg',
    form: 'Capsule',
    category: 'Antibiotic',
    price: 9.50,
    stockStatus: 'LOW_STOCK',
    quantity: 7,
    batchNo: 'AMX-2026-G9',
    expiryDate: '2027-05-10',
    prescriptionRequired: true
  },
  {
    id: 'med-04',
    facilityId: 'fac-pharm-01',
    facilityName: 'Apollo 24x7 Super Care Chemist',
    name: 'Glucophage XR',
    genericName: 'Metformin HCl',
    dosage: '1000mg',
    form: 'Tablet',
    category: 'Antidiabetic',
    price: 18.50,
    stockStatus: 'IN_STOCK',
    quantity: 210,
    batchNo: 'MET-2026-K4',
    expiryDate: '2028-01-20',
    prescriptionRequired: true
  },
  {
    id: 'med-05',
    facilityId: 'fac-pharm-02',
    facilityName: 'Metro Health Pharmacy & MedStore',
    name: 'Metformin Extended Release',
    genericName: 'Metformin HCl',
    dosage: '1000mg',
    form: 'Tablet',
    category: 'Antidiabetic',
    price: 16.00,
    stockStatus: 'IN_STOCK',
    quantity: 95,
    batchNo: 'MET-2026-E1',
    expiryDate: '2027-11-12',
    prescriptionRequired: true
  },
  {
    id: 'med-06',
    facilityId: 'fac-pharm-03',
    facilityName: 'City Care Generic & Critical Drugs',
    name: 'Metformin Generic Low-Cost',
    genericName: 'Metformin HCl',
    dosage: '1000mg',
    form: 'Tablet',
    category: 'Antidiabetic',
    price: 13.00,
    stockStatus: 'OUT_OF_STOCK',
    quantity: 0,
    batchNo: 'MET-2026-X0',
    expiryDate: '2027-04-18',
    prescriptionRequired: true
  },
  {
    id: 'med-07',
    facilityId: 'fac-pharm-01',
    facilityName: 'Apollo 24x7 Super Care Chemist',
    name: 'Lipitor Cardiovascular',
    genericName: 'Atorvastatin Calcium',
    dosage: '20mg',
    form: 'Tablet',
    category: 'Cardiovascular',
    price: 24.00,
    stockStatus: 'IN_STOCK',
    quantity: 180,
    batchNo: 'ATV-2026-L1',
    expiryDate: '2027-12-01',
    prescriptionRequired: true
  },
  {
    id: 'med-08',
    facilityId: 'fac-pharm-02',
    facilityName: 'Metro Health Pharmacy & MedStore',
    name: 'Atorva Gold Standard',
    genericName: 'Atorvastatin Calcium',
    dosage: '20mg',
    form: 'Tablet',
    category: 'Cardiovascular',
    price: 22.50,
    stockStatus: 'IN_STOCK',
    quantity: 45,
    batchNo: 'ATV-2026-A3',
    expiryDate: '2027-10-15',
    prescriptionRequired: true
  },
  {
    id: 'med-09',
    facilityId: 'fac-pharm-01',
    facilityName: 'Apollo 24x7 Super Care Chemist',
    name: 'Ventolin HFA Inhaler',
    genericName: 'Albuterol / Salbutamol',
    dosage: '100mcg',
    form: 'Inhaler',
    category: 'Respiratory',
    price: 32.00,
    stockStatus: 'IN_STOCK',
    quantity: 38,
    batchNo: 'ALB-2026-V8',
    expiryDate: '2027-07-22',
    prescriptionRequired: true
  },
  {
    id: 'med-10',
    facilityId: 'fac-pharm-02',
    facilityName: 'Metro Health Pharmacy & MedStore',
    name: 'Asthalin Metered Dose Inhaler',
    genericName: 'Albuterol / Salbutamol',
    dosage: '100mcg',
    form: 'Inhaler',
    category: 'Respiratory',
    price: 28.50,
    stockStatus: 'LOW_STOCK',
    quantity: 3,
    batchNo: 'ALB-2026-S2',
    expiryDate: '2027-06-18',
    prescriptionRequired: true
  },
  {
    id: 'med-11',
    facilityId: 'fac-pharm-03',
    facilityName: 'City Care Generic & Critical Drugs',
    name: 'Salbutamol Pressurized Aerosol',
    genericName: 'Albuterol / Salbutamol',
    dosage: '100mcg',
    form: 'Inhaler',
    category: 'Respiratory',
    price: 26.00,
    stockStatus: 'OUT_OF_STOCK',
    quantity: 0,
    batchNo: 'ALB-2026-G1',
    expiryDate: '2027-03-30',
    prescriptionRequired: true
  },
  {
    id: 'med-12',
    facilityId: 'fac-pharm-01',
    facilityName: 'Apollo 24x7 Super Care Chemist',
    name: 'Lantus SoloStar Pen (100u/mL)',
    genericName: 'Insulin Glargine',
    dosage: '100 units/mL',
    form: 'Injection',
    category: 'Antidiabetic',
    price: 68.00,
    stockStatus: 'IN_STOCK',
    quantity: 24,
    batchNo: 'INS-2026-L9',
    expiryDate: '2027-04-12',
    prescriptionRequired: true
  },
  {
    id: 'med-13',
    facilityId: 'fac-pharm-03',
    facilityName: 'City Care Generic & Critical Drugs',
    name: 'Paracetamol Rapid Antipyretic',
    genericName: 'Acetaminophen / Paracetamol',
    dosage: '650mg',
    form: 'Tablet',
    category: 'Analgesic',
    price: 4.50,
    stockStatus: 'IN_STOCK',
    quantity: 320,
    batchNo: 'PCM-2026-P3',
    expiryDate: '2028-06-01',
    prescriptionRequired: false
  },
  {
    id: 'med-14',
    facilityId: 'fac-pharm-02',
    facilityName: 'Metro Health Pharmacy & MedStore',
    name: 'Azithromycin 500 Z-Pack',
    genericName: 'Azithromycin',
    dosage: '500mg',
    form: 'Tablet',
    category: 'Antibiotic',
    price: 19.80,
    stockStatus: 'IN_STOCK',
    quantity: 52,
    batchNo: 'AZI-2026-Z4',
    expiryDate: '2027-08-10',
    prescriptionRequired: true
  }
];

export const INITIAL_DIAGNOSTIC_TESTS = [
  {
    id: 'test-01',
    code: 'CMP-01',
    name: 'Comprehensive Metabolic & Blood Panel (CMP)',
    category: 'Pathology',
    description: 'Complete blood count (CBC), kidney markers, liver enzymes, electrolytes, and blood glucose index.',
    fastingHours: 10,
    preparation: 'Strict overnight 10-hour water-only fasting recommended prior to draw.',
    turnaround: '6 Hours',
    sampleType: 'Venous Blood (5 mL)',
    price: 45.00,
    icon: 'droplets'
  },
  {
    id: 'test-02',
    code: 'CXR-02',
    name: 'High-Resolution Digital Chest X-Ray (PA View)',
    category: 'Radiology',
    description: 'Detailed radiographic imaging for lungs, mediastinum, pleura, and cardiac silhouette evaluation.',
    fastingHours: 0,
    preparation: 'No fasting required. Avoid clothing with metallic buttons or jewelry.',
    turnaround: '2 Hours',
    sampleType: 'Radiographic Scan',
    price: 38.00,
    icon: 'activity'
  },
  {
    id: 'test-03',
    code: 'LIP-03',
    name: 'Advanced Lipid & Cardiovascular Profile',
    category: 'Biochemistry',
    description: 'Total cholesterol, HDL, LDL, VLDL, and Triglycerides with cardiovascular risk stratification.',
    fastingHours: 12,
    preparation: 'Strict 12-hour fasting. Abstain from alcohol 24 hours prior to sampling.',
    turnaround: '4 Hours',
    sampleType: 'Venous Blood (3 mL)',
    price: 29.00,
    icon: 'heart-pulse'
  },
  {
    id: 'test-04',
    code: 'HBA1C-04',
    name: 'Glycated Hemoglobin (HbA1c) Diabetic Monitor',
    category: 'Pathology',
    description: 'Gold-standard monitor assessing 3-month average glucose control for diabetic screening & management.',
    fastingHours: 0,
    preparation: 'No fasting required. Can be drawn anytime throughout clinic hours.',
    turnaround: '3 Hours',
    sampleType: 'Whole Blood EDTA',
    price: 22.00,
    icon: 'clipboard-pulse'
  },
  {
    id: 'test-05',
    code: 'THY-05',
    name: 'Thyroid Function Ultra-Profile (T3, T4, TSH)',
    category: 'Biochemistry',
    description: 'Total Triiodothyronine (T3), Free Thyroxine (T4), and Thyroid Stimulating Hormone (TSH).',
    fastingHours: 0,
    preparation: 'Early morning sample recommended. Take thyroid hormone tablets after the blood draw.',
    turnaround: '8 Hours',
    sampleType: 'Serum Blood',
    price: 34.00,
    icon: 'thermometer'
  },
  {
    id: 'test-06',
    code: 'USG-06',
    name: 'Ultrasound Whole Abdomen & Pelvis Screening',
    category: 'Radiology',
    description: 'Non-invasive acoustic imaging of liver, gallbladder, spleen, kidneys, pancreas, and bladder.',
    fastingHours: 6,
    preparation: '6-hour fasting prior to appointment. Drink 1 Liter of plain water 45 mins prior to maintain a full bladder.',
    turnaround: '1 Hour',
    sampleType: 'Sonographic Scan',
    price: 55.00,
    icon: 'shield-alert'
  }
];

export const INITIAL_SLOT_WINDOWS = [
  { id: 'sw-01', period: 'MORNING', window: '08:00 AM - 09:00 AM' },
  { id: 'sw-02', period: 'MORNING', window: '09:30 AM - 10:30 AM' },
  { id: 'sw-03', period: 'MORNING', window: '11:00 AM - 12:00 PM' },
  { id: 'sw-04', period: 'AFTERNOON', window: '01:30 PM - 02:30 PM' },
  { id: 'sw-05', period: 'AFTERNOON', window: '03:00 PM - 04:00 PM' },
  { id: 'sw-06', period: 'EVENING', window: '05:00 PM - 06:00 PM' },
  { id: 'sw-07', period: 'EVENING', window: '06:30 PM - 07:30 PM' }
];

export const INITIAL_BLOOD_INVENTORY = [
  {
    id: 'bld-01',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'O+',
    component: 'Packed Red Blood Cells (PRBC)',
    unitsAvailable: 42,
    rackCode: 'CRYOBANK-A / TANK-01',
    temperature: 3.8,
    screened: true,
    pathologist: 'Dr. Marcus Vance, MD (Chief Pathologist)',
    expiryDaysLeft: 28,
    statusLevel: 'OPTIMAL' // 'OPTIMAL', 'MODERATE', 'LOW', 'CRITICAL'
  },
  {
    id: 'bld-02',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'O-',
    component: 'Packed Red Blood Cells (Universal Donor)',
    unitsAvailable: 4,
    rackCode: 'CRYOBANK-A / TANK-02',
    temperature: 4.0,
    screened: true,
    pathologist: 'Dr. Marcus Vance, MD',
    expiryDaysLeft: 14,
    statusLevel: 'CRITICAL'
  },
  {
    id: 'bld-03',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'A+',
    component: 'Packed Red Blood Cells (PRBC)',
    unitsAvailable: 38,
    rackCode: 'CRYOBANK-B / TANK-01',
    temperature: 4.1,
    screened: true,
    pathologist: 'Dr. Elena Rostova, MD',
    expiryDaysLeft: 30,
    statusLevel: 'OPTIMAL'
  },
  {
    id: 'bld-04',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'A-',
    component: 'Packed Red Blood Cells (PRBC)',
    unitsAvailable: 7,
    rackCode: 'CRYOBANK-B / TANK-02',
    temperature: 3.9,
    screened: true,
    pathologist: 'Dr. Elena Rostova, MD',
    expiryDaysLeft: 18,
    statusLevel: 'LOW'
  },
  {
    id: 'bld-05',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'B+',
    component: 'Packed Red Blood Cells (PRBC)',
    unitsAvailable: 29,
    rackCode: 'CRYOBANK-C / TANK-01',
    temperature: 4.2,
    screened: true,
    pathologist: 'Dr. Marcus Vance, MD',
    expiryDaysLeft: 24,
    statusLevel: 'OPTIMAL'
  },
  {
    id: 'bld-06',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'B-',
    component: 'Packed Red Blood Cells (PRBC)',
    unitsAvailable: 3,
    rackCode: 'CRYOBANK-C / TANK-02',
    temperature: 4.0,
    screened: true,
    pathologist: 'Dr. Marcus Vance, MD',
    expiryDaysLeft: 12,
    statusLevel: 'CRITICAL'
  },
  {
    id: 'bld-07',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'AB+',
    component: 'Packed Red Blood Cells (Universal Recipient)',
    unitsAvailable: 22,
    rackCode: 'CRYOBANK-D / TANK-01',
    temperature: 4.0,
    screened: true,
    pathologist: 'Dr. Elena Rostova, MD',
    expiryDaysLeft: 35,
    statusLevel: 'OPTIMAL'
  },
  {
    id: 'bld-08',
    facilityId: 'fac-bank-01',
    facilityName: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'AB-',
    component: 'Packed Red Blood Cells (PRBC)',
    unitsAvailable: 2,
    rackCode: 'CRYOBANK-D / TANK-02',
    temperature: 3.7,
    screened: true,
    pathologist: 'Dr. Elena Rostova, MD',
    expiryDaysLeft: 9,
    statusLevel: 'CRITICAL'
  },
  {
    id: 'bld-09',
    facilityId: 'fac-hosp-01',
    facilityName: 'St. Jude Academic Medical Center',
    bloodGroup: 'O-',
    component: 'Emergency Trauma Reserve',
    unitsAvailable: 2,
    rackCode: 'STJUDE-FRIDGE-01',
    temperature: 4.1,
    screened: true,
    pathologist: 'Dr. Sarah Lin (Lic #MED-8812)',
    expiryDaysLeft: 8,
    statusLevel: 'CRITICAL'
  },
  {
    id: 'bld-10',
    facilityId: 'fac-hosp-01',
    facilityName: 'St. Jude Academic Medical Center',
    bloodGroup: 'O+',
    component: 'General Surgery Reserve',
    unitsAvailable: 12,
    rackCode: 'STJUDE-FRIDGE-01',
    temperature: 4.0,
    screened: true,
    pathologist: 'Dr. Sarah Lin',
    expiryDaysLeft: 21,
    statusLevel: 'MODERATE'
  }
];

export const INITIAL_EMERGENCY_ALERTS = [
  {
    id: 'alt-01',
    hospitalId: 'fac-hosp-01',
    hospitalName: 'St. Jude Academic Medical Center',
    bloodGroup: 'O-',
    unitsNeeded: 2,
    urgency: 'CODE_RED_CRITICAL',
    title: 'Code Red Trauma: Multi-Vehicle Collision',
    summary: 'Massive transfusion protocol active for acute hemorrhagic shock patient in ICU Bay 3.',
    location: '450 University Blvd (Medical District)',
    postedAgo: '18 minutes ago',
    active: true
  },
  {
    id: 'alt-02',
    hospitalId: 'fac-hosp-02',
    hospitalName: 'Metropolitan Trauma & Surgical Center',
    bloodGroup: 'B-',
    unitsNeeded: 3,
    urgency: 'HIGH',
    title: 'Emergency Cardiovascular Bypass Support',
    summary: 'Immediate replenishment needed for urgent thoracic surgery with unanticipated coagulopathy.',
    location: '128 Grand Central Ave (Downtown)',
    postedAgo: '42 minutes ago',
    active: true
  },
  {
    id: 'alt-03',
    hospitalId: 'fac-hosp-01',
    hospitalName: 'St. Jude Academic Medical Center',
    bloodGroup: 'AB-',
    unitsNeeded: 1,
    urgency: 'HIGH',
    title: 'Pediatric Oncology Platelet / Red Cell Need',
    summary: 'Subspecialty pediatric supportive therapy in Wing 2B.',
    location: '450 University Blvd (Medical District)',
    postedAgo: '1 hour ago',
    active: true
  }
];

export const INITIAL_DONORS = [
  {
    id: 'don-01',
    fullName: 'Jonathan Reed',
    bloodGroup: 'O-',
    age: 32,
    weightKg: 74.5,
    lastDonationDate: '2026-06-12',
    district: 'Downtown Metro',
    maskedPhone: '98124*****',
    emergencyStandby: true,
    status: 'ACTIVE_STANDBY'
  },
  {
    id: 'don-02',
    fullName: 'Ananya Sharma',
    bloodGroup: 'B-',
    age: 27,
    weightKg: 58.0,
    lastDonationDate: '2026-05-14',
    district: 'North Midtown',
    maskedPhone: '97441*****',
    emergencyStandby: true,
    status: 'ACTIVE_STANDBY'
  },
  {
    id: 'don-03',
    fullName: 'Carlos Mendez',
    bloodGroup: 'AB-',
    age: 41,
    weightKg: 81.2,
    lastDonationDate: '2026-06-28',
    district: 'Chelsea District',
    maskedPhone: '98902*****',
    emergencyStandby: true,
    status: 'ACTIVE_STANDBY'
  }
];

export const INITIAL_HOSPITAL_REQUESTS = [
  {
    id: 'req-01',
    requisitionId: 'REQ-2026-STJUDE-9041',
    requestingHospital: 'St. Jude Academic Medical Center',
    fulfillingFacility: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'O-',
    component: 'Packed Red Blood Cells (PRBC)',
    units: 2,
    priority: 'CODE_RED_CRITICAL',
    rationale: 'Severe hypovolemic shock following blunt polytrauma. Type-specific crossmatch in progress.',
    status: 'COURIER_DISPATCHED', // 'PENDING_REVIEW', 'STOCK_MATCHED', 'COURIER_DISPATCHED', 'IN_TRANSIT', 'DELIVERED'
    trackingToken: 'PP-TX-7994-O-NEG-COLD-CHAIN-VERIFIED-9812A',
    tempCelsius: 3.8,
    dispatchedTime: '12 mins ago',
    etaMinutes: 13,
    doctor: 'Dr. Sarah Lin (Lic #MED-8812)'
  },
  {
    id: 'req-02',
    requisitionId: 'REQ-2026-METRO-4412',
    requestingHospital: 'Metropolitan Trauma & Surgical Center',
    fulfillingFacility: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'B-',
    component: 'Packed Red Blood Cells (PRBC)',
    units: 2,
    priority: 'HIGH',
    rationale: 'Aortic valve replacement post-op coagulopathy management.',
    status: 'STOCK_MATCHED',
    trackingToken: 'PP-TX-6621-B-NEG-COLD-CHAIN-ALLOCATED-4421B',
    tempCelsius: 4.1,
    dispatchedTime: 'Pending Courier Pickup',
    etaMinutes: 30,
    doctor: 'Dr. Robert Hall (Lic #MED-5401)'
  },
  {
    id: 'req-03',
    requisitionId: 'REQ-2026-STJUDE-8890',
    requestingHospital: 'St. Jude Academic Medical Center',
    fulfillingFacility: 'Regional Central Blood & Plasma Repository',
    bloodGroup: 'A+',
    component: 'Packed Red Blood Cells (PRBC)',
    units: 4,
    priority: 'ROUTINE',
    rationale: 'Scheduled elective bilateral hip arthroplasty reserved reserve pool.',
    status: 'DELIVERED',
    trackingToken: 'PP-TX-3310-A-POS-DELIVERED-ARCHIVE-5520Z',
    tempCelsius: 4.0,
    dispatchedTime: 'Completed (2h ago)',
    etaMinutes: 0,
    doctor: 'Dr. Sarah Lin (Lic #MED-8812)'
  }
];

export const COMPATIBILITY_RULES = {
  'O-': { canDonateTo: ['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+'], canReceiveFrom: ['O-'] },
  'O+': { canDonateTo: ['O+', 'A+', 'B+', 'AB+'], canReceiveFrom: ['O+', 'O-'] },
  'A-': { canDonateTo: ['A-', 'A+', 'AB-', 'AB+'], canReceiveFrom: ['A-', 'O-'] },
  'A+': { canDonateTo: ['A+', 'AB+'], canReceiveFrom: ['A+', 'A-', 'O+', 'O-'] },
  'B-': { canDonateTo: ['B-', 'B+', 'AB-', 'AB+'], canReceiveFrom: ['B-', 'O-'] },
  'B+': { canDonateTo: ['B+', 'AB+'], canReceiveFrom: ['B+', 'B-', 'O+', 'O-'] },
  'AB-': { canDonateTo: ['AB-', 'AB+'], canReceiveFrom: ['AB-', 'A-', 'B-', 'O-'] },
  'AB+': { canDonateTo: ['AB+'], canReceiveFrom: ['AB+', 'AB-', 'A+', 'A-', 'B+', 'B-', 'O+', 'O-'] }
};
